### ISSUE TITLE
bitcoin

### ISSUE THREAD

**Issue by rhd** [pderksen/WP-Stripe-Checkout#5]
Hi,

Do you plan on integrating the new bitcoin feature into this plugin?

https://stripe.com/bitcoin

**Comment by pderksen** [comment]
We started to do some research when it was announced, but hadn't determined how much work was involved yet.

If it's as easy for us to add the data-bitcoin="true" attribute to the output, then sure we can do it soon (and for this free version of the plugin).

If there's more to it than that, we'll probably include it in the Pro version but only if there's enough demand, and the timeline is unknown at this point.

I'm also uncertain as to what we'd need to change in the payment success & failure verbage the plugin outputs after a transaction.

If you'd like I can update the code real quick and you can beta test a simple edit to the plugin adding the data-bitcoin="true" attribute to see what happens. Let me know.

**Comment by rhd** [comment]
Sure, I could test it quick for you.

It would also be nice to have a checkbox (or something) in the settings which enabled/disabled bitcoin.

Thanks!

**Comment by pderksen** [comment]
I just created the branch `bitcoin-toggle` to test this out.

Grab the beta plugin download here to test:
https://github.com/pderksen/WP-Stripe-Checkout/archive/bitcoin-toggle.zip

Simply add the attribute `bitcoin=true` to your shortcode. Like this:

`[stripe name="My Store" description="My Product" amount="1999" bitcoin="true"]`

I didn't add a checkbox option in the settings quite yet.

Let me know if that works and if you think there's additional work that needs to be done.

Also, is there a way you can test this in a live environment?

Thanks for helping out!

**Comment by pderksen** [comment]
@rhd Let me know when you get a chance to try this out. I'd love to hear your thoughts.

Thanks!

**Comment by rhd** [comment]
I tested this with the free version and it worked fine. I then applied to changes manually to the pro version and for some reason this didn't show the bitcoin option.

So, my testing showed that the code from github worked great. 

If you push the change to the pro version, I'll do further testing with that.

**Comment by pderksen** [comment]
Great thanks for doing that.

I could definitely use your help beta testing on the Pro plugin as well. Could you shoot me an email at phil AT wpstripe.net to start the process?

**Comment by pderksen** [comment]
I'm also curious if anything's missing from the payment success page that needs to be there specifically for bitcoin.

**Comment by rhd** [comment]
email sent.

**Comment by pderksen** [comment]
Added to Lite & Pro plugins.
